### PR TITLE
COR:Correct global variable declaration

### LINKED ISSUE #89: Correct global variable declaration location
main.c 에서 전역변수를 선언, 초기화 하였는데
이를 declaration.c 파일로 옮깁시다.
(전역변수만 모아둠)

### PR DESCRIPTION
**Pull request by seohyeonKK**
Create file 'declaration.c' to declare global variables.
Change the declaration loaction of 'player1_turn', 'player2_turn',
'success', 'failure', 'player1', 'player2' variables from 'main.c' to
'declaration.c'.
Remove the useless statements about the global variable in
"declaration.h".

### CODE REVIEW

**Comment by mjseok** [comment]
leaderboard.c에서 ui.h도 include해야할 것 같아요~

**Comment by mjseok** [comment]
확인했습니당 merge합시다아

**Comment by cherry2030** [comment]
merge합시다^^*

**Comment by hanzzb** [comment]
merge gogo

**Pull request merged**
