### PR TITLE
COR:Fix the details of functions

### LINKED ISSUE #70: Fix the computer-related functions
컴퓨터와 관련된 함수를 다른 함수를 써서 구현하기

### LINKED ISSUE #71: Change the output
기호를 고를 때처럼 "Player1"이 출력되는 것을 없애주세요^^

### PR DESCRIPTION
**Pull request by seohyeonKK**
Rename isRight() to isRightInput().
Rename the parameters board_symbol[] of checkPosition() and
checkVacanvies() to game_board[].
Remove the output "Player1" from showResult() and chooseSymbol().
Change negative conditional statements into positive.
Change specific characters to meaningful characters in
checkValueOnComputer().
Change the duplicated code to function in PlayWithComputer().

### CODE REVIEW

**Comment by mjseok** [comment]
오오 좋아요! Merge합시당

**Comment by hanzzb** [comment]
playWithComputer()에서 symbol, someoneWin변수 선언 삭제해주세요!

**Comment by mjseok** [comment]
앗 좋아요! merge동의합니다!

**Comment by hanzzb** [comment]
좋아요 merge gogo~

**Comment by cherry2030** [comment]
이제 다 수정했군용~merge해요~~~

**Pull request merged**
